### ISSUE TITLE
Doesn't work with Jupyter

### ISSUE THREAD

**Issue by DavidNemeskey** [cjdrake/ipython-magic#5]
My version 6.1.0, and when I try to `%load_ext gvmagic`, I get the error message 'ImportError: No module named 'IPython.utils.warn''

**Comment by cjdrake** [comment]
Looks like maybe the `IPython.utils.warn` module was deprecated? I haven't exactly been keeping up-to-date on IPython/Jupyter development lately, so that wouldn't surprise me.
