### ISSUE TITLE
Could you make ipython-magic available via PyPI?

### ISSUE THREAD

**Issue by arne-cl** [cjdrake/ipython-magic#6]
Dear Chris,

could you please make ipython-magic available via PyPI?
So far, I have been able to use it via IPython's ``%install_ext`` magic, but that is [no longer available](https://github.com/ipython/ipython/issues/8634).

Best regards,
Arne

**Comment by cjdrake** [comment]
Have you tried using `pip install gvmagic` ?

**Comment by arne-cl** [comment]
Thank you! I didn't look for `gvmagic` but only for `ipython-magic` in PyPI. 
Maybe you could add a note to your README about the PyPI installation option.
